# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_contraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_usp_rf_data_converter_0_0/design_1_usp_rf_data_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usp_rf_data_converter_0_0 || ORIG_REF_NAME==design_1_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_0/design_1_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_99M_0/design_1_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_startup_0_0/design_1_startup_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_startup_0_0 || ORIG_REF_NAME==design_1_startup_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ctrl_snapshot_128k_0_0/design_1_ctrl_snapshot_128k_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ctrl_snapshot_128k_0_0 || ORIG_REF_NAME==design_1_ctrl_snapshot_128k_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uram_play128k_0_0/design_1_uram_play128k_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uram_play128k_0_0 || ORIG_REF_NAME==design_1_uram_play128k_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_0/design_1_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_0 || ORIG_REF_NAME==design_1_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_0 || ORIG_REF_NAME==design_1_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pl_sysref_0_0/design_1_pl_sysref_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pl_sysref_0_0 || ORIG_REF_NAME==design_1_pl_sysref_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_0_0/design_1_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_0_0 || ORIG_REF_NAME==design_1_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_1_0/design_1_axis_dwidth_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_1_0 || ORIG_REF_NAME==design_1_axis_dwidth_converter_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_0/design_1_axis_clock_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_0 || ORIG_REF_NAME==design_1_axis_clock_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_1/design_1_blk_mem_gen_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_1 || ORIG_REF_NAME==design_1_blk_mem_gen_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_1_1/design_1_axis_dwidth_converter_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_1_1 || ORIG_REF_NAME==design_1_axis_dwidth_converter_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_2 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ctrl_snapshot_128k_0_2/design_1_ctrl_snapshot_128k_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ctrl_snapshot_128k_0_2 || ORIG_REF_NAME==design_1_ctrl_snapshot_128k_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_1/design_1_axis_clock_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_1 || ORIG_REF_NAME==design_1_axis_clock_converter_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_2/design_1_blk_mem_gen_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_2 || ORIG_REF_NAME==design_1_blk_mem_gen_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_1_2/design_1_axis_dwidth_converter_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_1_2 || ORIG_REF_NAME==design_1_axis_dwidth_converter_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_3/design_1_axi_bram_ctrl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_3 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ctrl_snapshot_128k_0_3/design_1_ctrl_snapshot_128k_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ctrl_snapshot_128k_0_3 || ORIG_REF_NAME==design_1_ctrl_snapshot_128k_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_2/design_1_axis_clock_converter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_2 || ORIG_REF_NAME==design_1_axis_clock_converter_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_3/design_1_blk_mem_gen_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_3 || ORIG_REF_NAME==design_1_blk_mem_gen_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_1_3/design_1_axis_dwidth_converter_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_1_3 || ORIG_REF_NAME==design_1_axis_dwidth_converter_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_4/design_1_axi_bram_ctrl_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_4 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ctrl_snapshot_128k_0_4/design_1_ctrl_snapshot_128k_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ctrl_snapshot_128k_0_4 || ORIG_REF_NAME==design_1_ctrl_snapshot_128k_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_3/design_1_axis_clock_converter_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_3 || ORIG_REF_NAME==design_1_axis_clock_converter_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_4/design_1_blk_mem_gen_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_4 || ORIG_REF_NAME==design_1_blk_mem_gen_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_1_4/design_1_axis_dwidth_converter_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_1_4 || ORIG_REF_NAME==design_1_axis_dwidth_converter_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_5/design_1_axi_bram_ctrl_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_5 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ctrl_snapshot_128k_0_5/design_1_ctrl_snapshot_128k_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ctrl_snapshot_128k_0_5 || ORIG_REF_NAME==design_1_ctrl_snapshot_128k_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_4/design_1_axis_clock_converter_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_4 || ORIG_REF_NAME==design_1_axis_clock_converter_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_5/design_1_blk_mem_gen_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_5 || ORIG_REF_NAME==design_1_blk_mem_gen_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_1_5/design_1_axis_dwidth_converter_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_1_5 || ORIG_REF_NAME==design_1_axis_dwidth_converter_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_6 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ctrl_snapshot_128k_0_6/design_1_ctrl_snapshot_128k_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ctrl_snapshot_128k_0_6 || ORIG_REF_NAME==design_1_ctrl_snapshot_128k_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_5/design_1_axis_clock_converter_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_5 || ORIG_REF_NAME==design_1_axis_clock_converter_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_6/design_1_blk_mem_gen_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_6 || ORIG_REF_NAME==design_1_blk_mem_gen_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_1_6/design_1_axis_dwidth_converter_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_1_6 || ORIG_REF_NAME==design_1_axis_dwidth_converter_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_7/design_1_axi_bram_ctrl_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_7 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ctrl_snapshot_128k_0_7/design_1_ctrl_snapshot_128k_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ctrl_snapshot_128k_0_7 || ORIG_REF_NAME==design_1_ctrl_snapshot_128k_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_6/design_1_axis_clock_converter_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_6 || ORIG_REF_NAME==design_1_axis_clock_converter_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_7/design_1_blk_mem_gen_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_7 || ORIG_REF_NAME==design_1_blk_mem_gen_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_1_7/design_1_axis_dwidth_converter_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_1_7 || ORIG_REF_NAME==design_1_axis_dwidth_converter_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_8/design_1_axi_bram_ctrl_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_8 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ctrl_snapshot_128k_0_8/design_1_ctrl_snapshot_128k_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ctrl_snapshot_128k_0_8 || ORIG_REF_NAME==design_1_ctrl_snapshot_128k_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_7/design_1_axis_clock_converter_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_7 || ORIG_REF_NAME==design_1_axis_clock_converter_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_clock_converter_0_8/design_1_axis_clock_converter_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_clock_converter_0_8 || ORIG_REF_NAME==design_1_axis_clock_converter_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_2_0/design_1_system_ila_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_ila_2_0 || ORIG_REF_NAME==design_1_system_ila_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_1_2/design_1_system_ila_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_ila_1_2 || ORIG_REF_NAME==design_1_system_ila_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_51/design_1_s00_regslice_51.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_51 || ORIG_REF_NAME==design_1_s00_regslice_51} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_rs_w_1/design_1_auto_rs_w_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_1 || ORIG_REF_NAME==design_1_auto_rs_w_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_0 || ORIG_REF_NAME==design_1_m00_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m01_regslice_0/design_1_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m01_regslice_0 || ORIG_REF_NAME==design_1_m01_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_rs_0/design_1_auto_rs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_0 || ORIG_REF_NAME==design_1_auto_rs_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_rs_w_0/design_1_auto_rs_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_rs_w_0 || ORIG_REF_NAME==design_1_auto_rs_w_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_1 || ORIG_REF_NAME==design_1_auto_ds_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_52/design_1_s00_regslice_52.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_52 || ORIG_REF_NAME==design_1_s00_regslice_52} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
