# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wisig/Videos/MTS/RFSoC-MTS/mts/mts.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wisig/Videos/MTS/RFSoC-MTS/mts/mts.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wisig/Videos/MTS/RFSoC-MTS/mts/mts.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wisig/Videos/MTS/RFSoC-MTS/mts/mts.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
